name: we_hike
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/magnifying-glass-solid.svg
    - assets/hills.jpg
    - assets/Comfortaa Regular.ttf

  fonts:
     - family: Comfortaa
       fonts:
         - asset: assets/Comfortaa Regular.ttf